2019-02-22 14:40:35,344 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:77]
2019-02-22 14:40:49,153 ERROR: Exception on /search [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "d:\dev\microblog\venv\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "d:\dev\microblog\venv\app\models.py", line 18, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-02-22 14:42:12,285 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:77]
2019-02-22 14:42:22,713 ERROR: Exception on /search [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "d:\dev\microblog\venv\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "d:\dev\microblog\venv\app\models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-02-22 14:42:23,578 ERROR: Exception on /search [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "d:\dev\microblog\venv\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "d:\dev\microblog\venv\app\models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-02-22 14:47:25,737 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:77]
2019-02-22 14:47:36,550 ERROR: Exception on /search [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "d:\dev\microblog\venv\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "d:\dev\microblog\venv\app\models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-02-22 14:47:46,347 ERROR: Exception on /search [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "d:\dev\microblog\venv\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "d:\dev\microblog\venv\app\models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-02-22 14:48:59,811 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:77]
2019-02-22 14:49:05,833 ERROR: Exception on /search [GET] [in d:\dev\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\dev\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\dev\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\dev\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "d:\dev\microblog\venv\app\main\routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "d:\dev\microblog\venv\app\models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
TypeError: 'NoneType' object is not iterable
2019-02-22 14:51:57,871 INFO: Microblog startup [in d:\dev\microblog\venv\app\__init__.py:77]
